export const SET_ALERT = "SET_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const SEND_RESET_EMAIL = "SEND_RESET_EMAIL";
export const SEND_RESET_EMAIL_FAIL = "SEND_RESET_EMAIL_FAIL";

export const LOGOUT = "LOGOUT";

export const USER_LOADED = "USERLOADED";
export const AUTH_ERROR = "AUTH_ERROR";

export const ADD_CATEGORY = "ADD_CATEGORY";
export const DELETE_CATEGORY = "DELETE_CATEGORY";
export const DELETE_CATEGORY_ERROR = "DELETE_CATEGORY_ERROR";
export const ADD_CATEGORY_FAIL = "ADD_CATEGORY_FAIL";
export const GET_ALL_CATEGORIES = "GET_ALL_CATEGORIES";
export const GET_ALL_CATEGORIES_ERROR = "GET_ALL_CATEGORIES_ERROR";

export const ADD_BRAND = "ADD_BRAND";
export const DELETE_BRAND = "DELETE_BRAND";
export const DELETE_BRAND_ERROR = "DELETE_BRAND_ERROR";
export const ADD_BRAND_FAIL = "ADD_BRAND_FAIL";
export const GET_ALL_BRANDS = "GET_ALL_BRANDS";
export const GET_ALL_BRANDS_ERROR = "GET_ALL_BRANDS_ERROR";

export const ADD_BIKE = "ADD_BIKE";
export const ADD_BIKE_ERROR = "ADD_BIKE_ERROR";
export const FETCH_BIKE = "FETCH_BIKE";
export const FETCH_ALL_BIKES = "FETCH_ALL_BIKES";
export const FETCH_BIKE_ERROR = "FETCH_BIKE_ERROR";
export const DELETE_BIKE = "DELETE_BIKE";
export const DELETE_BIKE_ERROR = "DELETE_BIKE_ERROR";
export const UPDATE_BIKE = "UPDATE_BIKE";
export const UPDATE_BIKE_ERROR = "UPDATE_BIKE_ERROR";

export const GET_ALL_BIKES = "GET_ALL_BIKES_PRODUCTS_PAGE";
export const GET_ALL_BIKES_ERROR = "GET_ALL_BIKES_ERROR_PRODUCTS_PAGE";
export const GET_ALL_ACCESSORIES = "GET_ALL_ACCESSORIES_PRODUCTS_PAGE";
export const GET_ALL_ACCESSORIES_ERROR =
  "GET_ALL_ACCESSORIES_ERROR_PRODUCTS_PAGE";

export const GET_SEARCH_RESULTS = "GET_SEARCH_RESULTS";
export const GET_SEARCH_RESULTS_ERROR = "GET_SEARCH_RESULTS_ERROR";

export const ADD_PINCODE = "ADD_PINCODE";
export const ADD_PINCODE_FAIL = "ADD_PINCODE_FAIL";
export const FETCH_PINCODES = "FETCH_PINCODES";
export const FETCH_PINCODES_FAIL = "FETCH_PINCODES_FAIL";
export const CHECK_PINCODE = "CHECK_PINCODE";
export const CHECK_PINCODE_FAIL = "CHECK_PINCODE_FAIL";

export const ADD_TO_CART = "ADD_TO_CART";

export const CREATE_ORDER = "CREATE_ORDER";

export const DELETE_ORDER = "DELETE_ORDER";
export const DELETE_ORDER_ERROR = "DELETE_ORDER_ERROR";
export const GET_ALL_ORDERS = "GET_ALL_ORDERS";
export const GET_ALL_USER_ORDERS = "GET_ALL_USER_ORDERS";
export const GET_ALL_ORDERS_ERROR = "GET_ALL_ORDERS_ERROR";
